import { library } from '@fortawesome/fontawesome-svg-core'
import { fab } from '@fortawesome/free-brands-svg-icons'
import {
    faArrowDown,
    faArrowUp,
    faArrowsAlt,
    faArrowsAltV,
    faArrowAltCircleDown,
    faAngleDoubleRight,
    faAngleDoubleLeft,
    faBackspace,
    faCaretDown,
    faClipboard,
    faClipboardList,
    faSearch,
    faFilter,
    faArrowLeft,
    faExclamation,
    faPaperPlane,
    faCheckCircle,
    faTimes,
    faEllipsisV,
    faEllipsisH,
    faMinus,
    faShare,
    faCog,
    faPaperclip,
    faChevronRight,
    faChevronDown,
    faChevronUp,
    faTrashAlt,
    faPen,
    faSpinner,
    faUpload,
    faPlus,
    faUndo,
    faCommentAlt,
    faInbox,
    faArchive,
    faUserFriends,
    faUser,
    faUsers,
    faBullhorn,
    faHistory,
    faFileAlt,
    faLink,
    faLevelUpAlt,
    faChalkboardTeacher,
    faClipboardCheck,
    faStar,
    faEdit,
    faCopy,
    faUndoAlt,
    faClock,
    faExclamationCircle,
    faQuestion,
    faQuestionCircle,
    faCheck,
    faHeart,
    faUserEdit,
    faSync,
    faBars,
    faEnvelope,
    faGift,
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faCamera,
    faPencilAlt,
    faRobot,
    faBan,
    faHammer,
    faBookmark,
    faFileExport,
    faBullseye,
    faDesktop,
    faMobileAlt,
    faExclamationTriangle,
    faExternalLinkAlt,
    faEraser,
    faBookReader,
    faEyeSlash,
    faCalendarAlt,
} from '@fortawesome/free-solid-svg-icons'

import {
    faCheckCircle as farCheckCircle,
    faEye as farEye,
    faCheckCircle as fasCheckCircle,
    faTimesCircle as fasTimesCircle,
    faPaperPlane as fasPaperPlane,
    faCommentAlt as fasCommentAlt,
    faClipboard as farClipboard,
    faCheckSquare as farCheckSquare,
    faStar as farStar,
    faEdit as farEdit,
    faClock as farClock,
    faHeart as farHeart,
    faBookmark as farBookmark,
    faCalendar as farCalendar,
    faEyeSlash as farEyeSlash,
    faCalendarAlt as farCalendarAlt,
} from '@fortawesome/free-regular-svg-icons'

export default () => library.add(
    fab,
    faArrowDown,
    faArrowUp,
    faArrowsAlt,
    faArrowsAltV,
    faArrowAltCircleDown,
    faAngleDoubleRight,
    faAngleDoubleLeft,
    faBackspace,
    faCaretDown,
    faClipboard,
    farClipboard,
    faClipboardList,
    faSearch,
    faFilter,
    faArrowLeft,
    faExclamation,
    faPaperPlane,
    faCheckCircle,
    farCheckCircle,
    faTimes,
    faEllipsisV,
    faEllipsisH,
    faMinus,
    farEye,
    faEyeSlash,
    farEyeSlash,
    faShare,
    fasCheckCircle,
    fasTimesCircle,
    faCog,
    faPaperclip,
    faChevronRight,
    faChevronDown,
    faChevronUp,
    faPen,
    faTrashAlt,
    faSpinner,
    faUpload,
    faPlus,
    faUndo,
    faCommentAlt,
    faInbox,
    fasPaperPlane,
    faArchive,
    faUserFriends,
    faUser,
    faUsers,
    faBullhorn,
    faHistory,
    faFileAlt,
    fasCommentAlt,
    faLink,
    faLevelUpAlt,
    farCheckSquare,
    faChalkboardTeacher,
    faClipboardCheck,
    faStar,
    farStar,
    faEdit,
    farEdit,
    faCopy,
    faUndoAlt,
    faClock,
    farClock,
    faQuestion,
    faQuestionCircle,
    faExclamationCircle,
    faCheck,
    faHeart,
    farHeart,
    faUserEdit,
    faSync,
    faEnvelope,
    faGift,
    faAngleDown,
    faBars,
    faAngleLeft,
    faAngleRight,
    faCamera,
    faPencilAlt,
    faRobot,
    faBan,
    faHammer,
    farBookmark,
    faBookmark,
    faFileExport,
    faBullseye,
    farCalendar,
    faDesktop,
    faMobileAlt,
    faExclamationTriangle,
    faExternalLinkAlt,
    faEraser,
    faBookReader,
    faCalendarAlt,
    farCalendarAlt,
)